version: '2'
services:
    testdemo-app:
        image: testdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testdemo-mysql:3306/testdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testdemo-mysql:
        extends:
            file: mysql.yml
            service: testdemo-mysql
